name: Performance Tests

on: [push]

jobs:
  run_tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential 
        sudo apt-get install -y manpages-dev
        python -m pip install --upgrade pip setuptools wheel
    - name: Get top 5 merges to master
      run: |
        pwd
        git clone https://github.com/acheshkov/program-slicing.git
        cd program-slicing
        pwd
        COMMIT_IDS=$(git log --merges --first-parent master --pretty=format:"%H" | head -n 5)
        cd ..
        pwd
        echo $COMMIT_IDS
        declare -a theArray

        while read -r COMMIT_IDS
        do
            theArray+=("$COMMIT_IDS")            
        done <<< "$COMMIT_IDS"

        for line in "${theArray[@]}"
        do
            echo "Running test for sha $line"
            ls
            [ ! -d "program-slicing" ] && git clone https://github.com/acheshkov/program-slicing.git
            cd program-slicing
            ls
            git checkout $i
            git diff slicing/block/block.py
            git submodule update --recursive --init
            python3 -m venv venv && source venv/bin/activate
            if [ -f requirements/default.txt ]; then pip install -r requirements/default.txt; fi
            pip3 install . && pip3 install pandas
            cd ..
            CUR_DIR=$(pwd)
            ls
            SCRIPT_PATH="${CUR_DIR}/performance_tests/test.py"
            DATASET_PATH="${CUR_DIR}/performance_tests/performance_dataset"
            python3 $SCRIPT_PATH --dataset_path=$DATASET_PATH --commit_id=$line
            rm -rf program-slicing && deactivate
        done

      id: get_commits
        
